### ISSUE TITLE
Not using revisions

### ISSUE THREAD

**Issue by mikkeschiren** [wikimedia/composer-merge-plugin#101]
When I add a revision for a project in a "merged" composer.json, composer does not respect the commiit, like:

    "require": {
        "drupal/config_devel": "dev-8.x-1.x#d4cdd21"
    },

Instead of using revision `d4cdd21` it using the latest from HEAD. With a "normal" composer.json (not merged) it works and uses correct revision.

**Comment by webflo** [comment]
@mikkeschiren Please review PR #103

**Comment by webflo** [comment]
We have a related issue in for Drupal core. https://www.drupal.org/node/2652068
