### ISSUE TITLE
Remove PHP 5.3.3 from TravisCI

### ISSUE THREAD

**Issue by webflo** [wikimedia/composer-merge-plugin#104]
PHP 5.3.3 on Travis has some issues with openssl (https://docs.travis-ci.com/user/languages/php#PHP-installation). PHP 5.3 is EOL anyway maybe its enough if we keep testing against PHP 5.3 but remove 5.3.3?

**Comment by legoktm** [comment]
MediaWiki still supports 5.3.3, so we'll want to keep that until at least MediaWiki raises their version requirements ([bug](https://phabricator.wikimedia.org/T118932)).

I'm not sure about other projects that are using the plugin either...

**Comment by webflo** [comment]
Disabled TLS for PHP 5.3.3 in https://github.com/wikimedia/composer-merge-plugin/pull/107

**Comment by bd808** [comment]
Rather than removing the PHP 5.3.3 tests, @webflo added configuration in 35e677c5a53fb68a9a8283c59d7ab4ec5976822a that will disable the TLS feature when testing with PHP 5.3.3.
