### ISSUE TITLE
Warning requires composer-plugin-api 1.0.0

### ISSUE THREAD

**Issue by waandershz** [wikimedia/composer-merge-plugin#109]
"composer update" gives 'The "wikimedia/composer-merge-plugin" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example)'. Is this an issue?

**Comment by bd808** [comment]
Our composer.json has `"composer-plugin-api": "^1.0",` since v1.2.0. Are you using an older version of the plugin?

**Comment by waandershz** [comment]
Special:Version-page shows "wikimedia/composer-merge-plugin 1.3.0".

**Comment by waandershz** [comment]
Apparently we still used an old version (1.0), upgraded to 1.3 and now the message has disappeared.
