### ISSUE TITLE
Tag v1.3.1

### ISSUE THREAD

**Issue by bojanz** [wikimedia/composer-merge-plugin#111]
#102 has been merged, containing a critical bug fix for Drupal.
Basically, people who removed Drupal's .git repository (or used a dist package) were completely unable to install additional packages. That's now fixed, and we must update composer-merge-plugin that ships with Drupal. A new release would help :)

**Comment by bd808** [comment]
https://packagist.org/packages/wikimedia/composer-merge-plugin#v1.3.1
