### ISSUE TITLE
Does not update dependencies just installs or clone

### ISSUE THREAD

**Issue by andreasnrb** [wikimedia/composer-merge-plugin#121]
When I use this plugin Composer never updates dependencies it just installs or clones them when using git repo as dependency. Is this expected behavior or a bug?

**Comment by bd808** [comment]
I'm not sure I understand the problem statement. Can you give an example composer.json and merged config files that reproduce your issue along with a simple walk through?

**Comment by bd808** [comment]
Closed for inactivity.
