### ISSUE TITLE
 composer update : package listed for update is not installed. ignoring

### ISSUE THREAD

**Issue by PommeVerte** [wikimedia/composer-merge-plugin#128]
Hey guys,

If I manually add a dependency to the `composer.local.json` file and then `composer update "packagename"` I get the following output and the dependency is not installed:

```
user@hostname> composer update "packagename"
Package "packagename" listed for update is not installed. Ignoring.
...
```

This used to work so I'm guessing it has something to do with a change on the composer end?

Thanks for your help.

**Comment by bd808** [comment]
@PommeVerte can you give a sample composer.json and composer.local.json that you are trying this with and the complete list of steps that you are following? Also having the version of both Composer and composer-merge-plugin would help us recreate the issue and see if we can fix it.

**Comment by PommeVerte** [comment]
Sure, it'll be a little cryptic because all libraries used here are on private servers but here's what I've got once stripped down is:

```
Composer version 1.2.1 2016-09-12 11:27:19
```
```
composer-merge-plugin 5e447aa5a23f3763028cb861083513b3d5bb880b
```
**composer.json**:
```json
{
    "name": "some/othername",
    "description": "description",
    "homepage": "http://www.lala.com",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
    },
    "minimum-stability": "stable",
    "require": {
        "wikimedia/composer-merge-plugin": "dev-master",
    },
    "require-dev": {
    },
    "config": {
        "process-timeout": 1800,
        "github-protocols": [
            "https",
            "git",
            "ssh"
        ]
    },
    "repositories": [
    ],
    "extra": {
        "merge-plugin": {
            "include": [
                "composer.local.json"
            ]
        }
    }
}

```
**composer.local.json**:
```json
{
    "name": "some/name",
    "description": "Description",
    "homepage": "http://www.lala.com",
    "type": "project",
    "license": "Proprietary",
    "minimum-stability": "stable",
    "require": {
        "package/name": "dev-master"
    },
    "require-dev": {
    },
    "scripts": {
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "ssh://git@some/repo/url.git"
        }
    ],
    "extra": {
    }
}
```

**Comment by PommeVerte** [comment]
It also doesn't work if it's a packagist package btw.

**Comment by PommeVerte** [comment]
FYI If I place the package and repo directly into `composer.json` then it works as expected. I only get the error if I place my package inside the `composer.local.json` file.

**Comment by PommeVerte** [comment]
Any news? :)

**Comment by PommeVerte** [comment]
nvm I found the issue. It was a permission problem on the `composer.local.json` file.
