### ISSUE TITLE
outdated composer.json

### ISSUE THREAD

**Issue by theofidry** [wikimedia/composer-merge-plugin#130]
- have a `composer.json` with a dep
- have a `sub/composer.json` with `wikimedia/composer-merge-plugin` referencing the parent `composer.json`
- run `composer update` for both `composer.json`

And then if you add a dependence on the root, `composer.json`, running `composer update` on the child will give `[inheritance-plugin] Already merged ../../composer.json` so the new dep added to the root won't be added to the child.

**Comment by theofidry** [comment]
Actually even with rm the `sub/vendor` it still failed, or rather, the json was merged but it all the deps were not installed correctly and running an update a second time solved the issue...

**Comment by bd808** [comment]
The specific message you quote seems to be from your fork of composer-merge-plugin. Can you provide a details example that reproduces the issue using the plain composer-merge-plugin? Ideally this will be a set of composer.json files and exact cli instructions used along with the version of Composer and composer-merge-plugin that are being used.

**Comment by theofidry** [comment]
I couldn't reproduce the issue even with my plugin in an isolated environment. It's possible it's due to a weird machine state or something. Is there any cache done somewhere in the plugin? Anyway closing this, will re-open if I can find anything on it.
