### ISSUE TITLE
Support merging of config.preferred-install

### ISSUE THREAD

**Issue by GaryJones** [wikimedia/composer-merge-plugin#132]
My simplified site `composer.json` is as follows:

```json
{
  "require": {
    "wikimedia/composer-merge-plugin": "^1.3"
  },
  "config": {
    "vendor-dir": "wp-content/vendor",
    "optimize-autoloader": true
  },
  "extra": {
    "merge-plugin": {
      "include": "composer.local.json"
    }
  }
}
```

This is setup for production.

I'd like to be able to use the `composer.local.json` to specify which sources should be pulled in when installing locally (so I can work on the custom packages locally). This would be my `composer.local.json`:

```json
{
  "config": {
    "preferred-install": {
      "foo/*": "source",
    }
  }
}
```
Sadly, it appears that the `config` section is not merged, so `preferred-install` is not being seen. Is this something that can be added please? Like #48, but for the config section.

**Comment by EugenMayer** [comment]
I need of a similar thing, needed to merge config for splitting up definitions of the "core" package and its vendor config

**Comment by ThaDaVos** [comment]
Need the same thing, thinking it already works.... sadly it does not
