### ISSUE TITLE
incompatibility with fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by cronfy** [wikimedia/composer-merge-plugin#133]
I use fxp/composer-asset-plugin to set up where to place bower and npm assets - instead of `vendor/bower-assets` I configure composer to put it to `vendor/bower`, same with npm.

Configuration is made via `"extra": { "asset-installer-paths": {...} } `

With composer-merge-plugin, when configuration of `asset-installer-paths` is described not in root composer.json, but in one of included files, it does not work.

# Example:

File structure:

 * src/
   * a/
     * composer.json
   * composer.json

Contents of `src/composer.json`:

```
{
  "require": {
    "wikimedia/composer-merge-plugin": "dev-master"
  },
  "extra": {
    "merge-plugin": {
      "require": [
        "a/composer.json"
      ],
      "replace": true,
      "merge-extra": true,
      "merge-extra-deep": true
    }
  }
}
```

Contents of `src/a/composer.json`:

```
{
  "require": {
    "bower-asset/punycode": "1.3.*"
  },

  "extra": {
    "asset-installer-paths": {
      "bower-asset-library": "vendor/bower"
    }
  }
}
```

When I run `composer install` from `src/`, bower assets go to `vendor/bower-assets` (which is against my configuration).

If I move `extra` part of `src/a/composer.json` to root `src/composer.json`, assets go to `vendor/bower`, as expected.

https://github.com/wikimedia/composer-merge-plugin/pull/131 did not fix it :(

**Comment by bd808** [comment]
The `Fxp\Composer\AssetPlugin\FxpAssetPlugin` class grabs its configuration in the `Composer\Plugin\PluginInterface::activate()` method. Each registered plugin is activated **before** the `PluginEvents::INIT` event is triggered, so there is no way that composer-merge-plugin can change configuration seen by fxp/composer-asset-plugin.

**Comment by bd808** [comment]
I'm going to close this as there is nothing that we can do to change the implementation of another plugin. @cronfy, feel free to reference this issue if you decide to pursue some change upstream with the fxp/composer-asset-plugin project.

**Comment by cronfy** [comment]
Thanks for the explaination. I found another solution instead of fxp-composer plugin - it is https://asset-packagist.org/ . While it does not have an option to put assets to `vendor/bower`, it has instruction for Yii2, and since I am using Yii2 too, the problem was resolved.
