### ISSUE TITLE
Allow included files to include other files

### ISSUE THREAD

**Issue by bd808** [wikimedia/composer-merge-plugin#15]
Discussion from <https://gerrit.wikimedia.org/r/#/c/182323/>:
> > "extensions/*/composer.json" can also be added to composer.local.json, right?
>
> With version 0.5.0 of the merge plugin, no. At the moment the plugin will only take configuration directives from the top level composer.json file.

Initially I thought that it would be important for the root package maintainer to be able to completely control which globs were scanned for additional includes. After seeing some discussion on the [patch to include support in MediaWiki](https://gerrit.wikimedia.org/r/#/c/182323/) and further reflection, I'm coming around to the idea of nested includes under the deployer's control.

I think there are a few details to work out before diving into implementation:
- I'm not sure if recursion is needed or if it would be sufficient for only includes specified by first level includes to be processed. Whether this would make implementation easier one way or another remains to be seen.
- It may be useful to add an additional configuration option that allows this feature to be turned on or off by the root package manager. I'm thinking something like `extra.merge-plugin.recurse = true`. If this option is created, it should probably be available at each level where recursive includes could be processed.
- If controlled by a configuration flag, should the feature default to being enabled or disabled?
- If recursive includes are allowed how hard should we work to avoid loops? Would it be reasonable just to stop and emit an error if more than `N` files are processed?

@Nikerabbit do you have thoughts on this topic?

**Comment by Nikerabbit** [comment]
Personally, I was planning to advocate that all MediaWiki extensions, which have composer dependencies, to be made composer ready and submitted to packagist so that I/anyone can install them without needing to add any extensions/*/composer.json.

There are some more hurdles that most extensions do not have any "releases" other than REL branches, which makes update few and far between, unless dev-master is used(?).

**Comment by bd808** [comment]
Getting any extension that uses Composer itself to be installable via Composer seems like a good start for sure.

I think the versioning question is interesting as well. My modern MW deploy experience is mostly limited to "run the leading edge of git" so I'm not well in tune with the various problems that I'm sure exist with attempting to decide when to update extensions and what version to update them to. Back in the olden days when I was running MW behind corporate firewalls, upgrading MW was a once-every-year-or-two thing and would usually involve a complete reinstall on new hardware followed by restoring a database backup.

**Comment by Krinkle** [comment]
I agree that the perspective of using composer, managing dependencies and installing MediaWiki extensions; it'd be nice to use composer completely for that and not have LocalSettings `require_once` anymore for that. However I see at least two issues:

* Releases (as @Nikerabbit mentions). This isn't hard to solve. We can follow dev-master in most cases. And for releases, same as we do already. Whenever we create the REL_X branch, also tag vX.0. Extensions with their own versioning scheme can opt-out of this, just like is the case now.
* Development. This looks harder to solve. How can one install extensions locally via composer and yet have an easy way to maintain branches, patches and local working trees.

A few thoughts:

Right now I have a check out of mediawiki/core and mediawiki/extensions as sibling, and use `require_once $IP/../extensions/Foo/Foo.php` in LocalSettings.php (with custom wgExtensionAssetsPath, naturally). This also to keep core/extensions clean for when checking out wmf-branches.

Even if Composer has an easy way of putting a git clone inside `vendor/`, that doesn't seem desirable as it'd probably be hard to not accidentally overwrite when switching between stable versions, and checking out wmf branches vs local dev setup.

**Comment by bd808** [comment]
> Even if Composer has an easy way of putting a git clone inside vendor/, that doesn't seem desirable as it'd probably be hard to not accidentally overwrite when switching between stable versions, and checking out wmf branches vs local dev setup.

Git clone is exactly what using a "dev-master" sort of composer version requirement does. And if the extension declares itself as type "mediawiki-extension" it will actually clone into $IP/extensions (or $IP/skins for type "mediawiki-skin") instead of $IP/vendor. Those clones can then be manipulated locally and composer even has a command (`composer status`) that will show you which composer managed git clones are dirty with respect to upstream. It won't magically keep you from messing things up when switching branches on core, but that takes a very specialized setup as you describe. MediaWiki-Vagrant does not go to these lengths and works largely like a purely Composer managed setup could work.

I'm not personally sold that Composer is the best way to manage extensions, but I agree with @Nikerabbit that any extension that depends on Composer managed libraries should itself be installable via Composer. I also think that the merge plugin could be used to help those that are installing the same extensions via git cloning. That's where allowing composer.local.json to declare additional includes would come in handy.

**Comment by bd808** [comment]
I'd like to add the `extra.merge-plugin.recurse = false` functionality to allow a package to disable this feature if desired.
