### ISSUE TITLE
Use from repository?

### ISSUE THREAD

**Issue by marktopper** [wikimedia/composer-merge-plugin#152]
Would it be possible to use this plugin from a repository?

Example I have my `composer.json` file:
```
{
    "repositories": [
    	{
    		"type": "path",
    		"url": "hooks"
    	}
    ],
    "require": {
    	"hooks": "dev-master"
    }
}
```
And then I have my `hooks/composer.json` file:
```
{
    "name": "hooks",
    "extra": {
        "merge-plugin": {
            "include": [
                "test2/composer.json"
            ],
            "require": [
                "test/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "ignore-duplicates": false,
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-scripts": false
        }
    }
}
```

Currently it does not seem to run the `merge-plugin` for the repository.

**Comment by bd808** [comment]
I don't see anything in that configuration that actually installs composer-merge-plugin by requiring the package. Even if that were corrected however, composer-merge-plugin must read an extra.merge-plugin configuration block from the root `composer.json`. There is no reasonable way that the plugin can traverse the composer.json information supplied by other packages at runtime to discover additional configuration.
