### ISSUE TITLE
Release 1.4.1

### ISSUE THREAD

**Issue by grasmash** [wikimedia/composer-merge-plugin#153]
github.com/acquia/blt has relied on dev-master for a few months now and has been using the new `ignore-duplicates` feature without issue. This suggests that master is stable enough for a 1.4.1 tag.

It would be much appreciated if this could be released, as relying on `dev-master` can be problematic.

Thanks!

**Comment by bd808** [comment]
`{{done}}` https://github.com/wikimedia/composer-merge-plugin/releases/tag/v1.4.1

Thanks for the poke and the testing.

**Comment by grasmash** [comment]
Thank you!
