### ISSUE TITLE
Ignores path repositories

### ISSUE THREAD

**Issue by vercotux** [wikimedia/composer-merge-plugin#156]
I just tried merging a path repository, but it seems to have completely ignored it because none of the packages were found.

**composer.json**:

```
{
    "require": {
        "wikimedia/composer-merge-plugin": "dev-master",
        "mydeps/my-dep-x": "*"
    },
    "extra": {
        "merge-plugin": {
            "repositories": [
                "composer.repos.json"
            ]
        }
    }
}
```

**composer.repos.json**:

```
{"repositories": [
        {
                "type": "path",
                "url": "~/mydeps/my-dep-*"
        }
]}
```

If I simply move the path repository into the main composer.json, everything works fine.

**Comment by far-blue** [comment]
I don't know if this will fix things or if it was just a typo in your issue but in the "extra" section, the "repositories" key should be "include"

**Comment by vercotux** [comment]
@far-blue That was it! Thank you.
