### ISSUE TITLE
include/require remote files

### ISSUE THREAD

**Issue by claudiu-cristea** [wikimedia/composer-merge-plugin#172]
I need this plugin but I need to merge repositories from a remote composer file. It seems that right now, the plugin is only able to read from the filesystem.

**Comment by bd808** [comment]
That is correct. The workflow that would be required to fetch configuration from remote sources, process it, and include the results in a single composer run (or even 2 runs really) is more complexity than the plugin is intended to handle. Such support would really require the core functionality provided by the plugin to be integrated into the core composer application upstream.
