### ISSUE TITLE
[FR] Add merge `autoload` and resolve paths

### ISSUE THREAD

**Issue by leevigraham** [wikimedia/composer-merge-plugin#18]
It would be great if this addon also supported merging of PSR-4 autoload classes:

    "autoload": {
        "psr-4": {
            "Boardworld\\": "app/third_party/boardworld/src/"
        }
    }

Additionally relative paths in included composer files should have their paths resolved correctly.

**Comment by cweagans** [comment]
It looks like this is not possible. From what I can see, Composer doesn't provide a way to manipulate the autoload settings like it does with requires, stability flags, etc.

@bd808 Have you looked into this at all?

**Comment by bd808** [comment]
@cweagans No, I haven't looked into what the feature would entail. I'm actually a bit confused about the use case here. Perhaps a more detailed explanation of the usage scenario by you or @leevigraham would help us decide if this is possible or not via Composer as it exists today.

The primary use case for the current plugin is dealing with projects such as MediaWiki which ship a composer.json but may also be enhanced by adding additional Composer managed packages. I haven't tried to use it to merge other packages that are already present on the local system.

**Comment by cweagans** [comment]
So my use case is something like this:

My root composer.json requires `drupal/core`. The composer.json for drupal/core is here: https://github.com/tstoeckler/drupal-core/blob/8.0.x/composer.json. There's a bunch of autoload stuff specified in that composer.json, and I want to make sure that the autoloader is going to be aware of the Drupal classmap and such.

**Comment by bd808** [comment]
Why wouldn't you just `"require": { "drupal/core": "dev-master" }` or whatever version you need either directly in your top level composer.json or via a merged composer.json?

Here's an example:
* [MediaWiki's composer.json](https://github.com/wikimedia/mediawiki/blob/b594c133f3a751e0729c0052a65985f17c6b7fd1/composer.json#L64-L70)
* composer.local.json
```
{
    "require": {
        "monolog/monolog": "1.12.0"
    }
}
```

If you wanted to use a project that you already have locally cloned then you could include a [repository](https://getcomposer.org/doc/05-repositories.md#vcs) in the merged composer.json file that pointed to the local clone as the source for the package.

**Comment by leevigraham** [comment]
My use case is:

I use a CMS and I wanted to install plugins via the root composer.json. I ran into issues when one of the plugins composer.json files added it's own psr-4 autoloading.

The root composer json resolved all the dependencies correctly but not the additional namespaces. When the plugin tried to call a namespaced class with a namespace it defined in it's composer.json the namespace could not be found because the root composer.json didn't define it.

**Comment by brunogaspar** [comment]
+1 I would actually appreciate this, my use case is kinda the same as @leevigraham.

Will see if i can have a bit of time to look into it as well, but basically all that needs to happen is to merge in the autoload from let's say a module composer.json into the main composer.json, not sure if it's doable Composer wise, but if the requires work, the autoload should work too, i guess.

**Comment by JeroenDeDauw** [comment]
+1, this is also useful for various MediaWiki extensions

**Comment by JeroenDeDauw** [comment]
> It looks like this is not possible. From what I can see, Composer doesn't provide a way to manipulate the autoload settings like it does with requires, stability flags, etc.

Yeah, no setter there. Perhaps doing something hacky like creating a new package definition and adding that will work? I'm going to investigate a bit.

**Comment by hashar** [comment]
Thank you @JeroenDeDauw !

**Comment by JeroenDeDauw** [comment]
I'm quite confused now. Originally I was surprised this did not work out of the box. After a colleague told me it did not, and seeing the comments on this issue, I figured this was wrong and started with that PR. Now by doing manual testing for this PR I've found that the behaviour I was trying to add seems to be already there.

https://asciinema.org/a/bw5hd3bp5m3i25zz2kmeungn7

That's the MediaWiki `composer.json` file plus a `composer.json.local` with the SubPageList MediaWiki extension. This extension uses PSR4, as shown with a cat. And as also shown, this PSR4 ends up in the generated autoloader as expected.

Am I misunderstanding what this issue is about? Did I miss some kind of issue that makes the generated autoload actually not work?

**Comment by adamwathan** [comment]
@JeroenDeDauw:

Try cloning this repo: https://github.com/adamwathan/composer-merge-test/

You'll see here inside the `project` directory, I have to manually autoload the `package` folder: https://github.com/adamwathan/composer-merge-test/blob/master/project/composer.json#L12-L16

If you remove those lines and run a `composer update` in the `project` folder, it will not add the `package` code to the autoloader.

**Comment by JeroenDeDauw** [comment]
Yeah, ok, that makes sense. That use case is quite different from mine though, so I do not actually have use for this. I however see how it can be useful.

**Comment by JeroenDeDauw** [comment]
@adamwathan I wrapped up my PR since it was basically done anyway and verified that it works using your example repo. https://github.com/wikimedia/composer-merge-plugin/pull/29

**Comment by adamwathan** [comment]
@JeroenDeDauw Fantastic!

**Comment by leevigraham** [comment]
Excellent. Thanks for everyones hard work on this.
