### ISSUE TITLE
Fix and re-enable ocular code coverage upload

### ISSUE THREAD

**Issue by reedy** [wikimedia/composer-merge-plugin#200]
Currently it results in a "Guzzle\Common\Exception\InvalidArgumentException Invalid handle provided"

**Comment by reedy** [comment]
Possibly fixed in https://github.com/wikimedia/composer-merge-plugin/commit/d2ff7afbf1909f96963e60877fb553b8b963aca2

**Comment by noplanman** [comment]
@reedy sorry for the necroposting, but I'm running into this issue too and your linked commit didn't seem to have a fix for this. Just wondering if you have any extra insight as to what was causing this?
