### ISSUE TITLE
Proposal: Drop PHP < 7.4 support

### ISSUE THREAD

**Issue by reedy** [wikimedia/composer-merge-plugin#241]
https://www.php.net/supported-versions.php

PHP 7.2 is EOL since late 2020, PHP 7.3 is EOL since late 2021 and PHP 7.4 is still currently in (security) support, till late 2022.

> This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022. For more details, see https://github.com/actions/runner-images/issues/6002

This makes life easier when the above happens.

**Comment by bd808** [comment]
👍 Another reasonable change to include in a 3.0 release.
