### ISSUE TITLE
Fatal error on composer run - Call to undefined method Composer\Package\RootAliasPackage::setStabilityFlags

### ISSUE THREAD

**Issue by astax-t** [wikimedia/composer-merge-plugin#26]
I'm getting a fatal error when trying to run "composer update" or "composer install":

Fatal error: Call to undefined method Composer\Package\RootAliasPackage::setStabilityFlags() in ....web\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php on line 312

Looking at the code, the function `mergeStabilityFlags ` takes `RootPackageInterface` as its argument, but this interface doesn't have method setStabilityFlags. It exists only in `RootPackage`, but not in `RootAliasPackage` (both implement `RootPackageInterface`).

I don't fully understand how this works in composer and when `RootAliasPackage` is used instead of `RootPackage`, so can't fix it properly. I can add `if ($root instanceof RootPackage)` in `mergeStabilityFlags`, but not sure if it's really correct fix.

**Comment by legoktm** [comment]
What version of composer are you using? Is your composer.json and the ones you're trying to merge available somewhere to help reproduce?

**Comment by astax-t** [comment]
I'm using the very latest available version of composer - just run composer self-update.

I could not replicate the problem with a simple set of files - seems to happen only when composer.json is in git repository.

my composer.json:
```
 {
    "require": {
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "extra": {
        "merge-plugin": {
            "include": [
                "composer.local.json"
            ]
        },
        "branch-alias": {
            "dev-master": "8.0.x-dev"
        }
    }
}
```

composer.local.json:
```
{
	"require": {
		"php": ">=5.4.0,<5.6.0"
	}
}
```


And I also captured the backtrace now:


Fatal error: Call to undefined method Composer\Package\RootAliasPackage::setStabilityFlags() in D:\hosts\web2\1\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php on line 312

Call Stack:
    0.0057     406256   1. {main}() C:\Devtools\Composer\composer.phar:0
    0.0060     409056   2. require('phar://C:/Devtools/Composer/composer.phar/bin/composer') C:\Devtools\Composer\composer.phar:25
    0.0455    4109368   3. Composer\Console\Application->run() phar://C:/Devtools/Composer/composer.phar/bin/composer:43
    0.0496    4479264   4. Symfony\Component\Console\Application->run() phar://C:/Devtools/Composer/composer.phar/src/Composer/Console/Application.php:83
    0.0511    4623888   5. Composer\Console\Application->doRun() phar://C:/Devtools/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0535    4731480   6. Symfony\Component\Console\Application->doRun() phar://C:/Devtools/Composer/composer.phar/src/Composer/Console/Application.php:146
    0.0537    4731872   7. Symfony\Component\Console\Application->doRunCommand() phar://C:/Devtools/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0537    4732296   8. Symfony\Component\Console\Command\Command->run() phar://C:/Devtools/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0547    4736040   9. Composer\Command\UpdateCommand->execute() phar://C:/Devtools/Composer/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    0.1900    9218088  10. Composer\Installer->run() phar://C:/Devtools/Composer/composer.phar/src/Composer/Command/UpdateCommand.php:140
    0.1925    9203528  11. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar://C:/Devtools/Composer/composer.phar/src/Composer/Installer.php:194
    0.1929    9214448  12. Composer\EventDispatcher\EventDispatcher->doDispatch() phar://C:/Devtools/Composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:91
    0.1931    9215296  13. call_user_func:{phar://C:/Devtools/Composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:151}() phar://C:/Devtools/Composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:151
    0.1932    9215496  14. Wikimedia\Composer\MergePlugin->onInstallOrUpdate() phar://C:/Devtools/Composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:151
    0.1932    9216808  15. Wikimedia\Composer\MergePlugin->mergePackages() D:\hosts\web2\1\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php:147
    0.1933    9217472  16. Wikimedia\Composer\MergePlugin->loadFile() D:\hosts\web2\1\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php:184
    0.1943    9224696  17. Wikimedia\Composer\MergePlugin->mergeRequires() D:\hosts\web2\1\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php:206
    0.1943    9224808  18. Wikimedia\Composer\MergePlugin->mergeStabilityFlags() D:\hosts\web2\1\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php:263

**Comment by astax-t** [comment]
The error can be replicated by creating an empty git repository, adding and committing the composer.json and composer.local.json files from the comment above and then running `composer update` twice.

The first time composer finishes successfully, but doesn't install anything from the composer.local.json (btw, is this another bug?). The second time it actually processes .local.json and crashes.

**Comment by bd808** [comment]
> The first time composer finishes successfully, but doesn't install anything from the composer.local.json (btw, is this another bug?). The second time it actually processes .local.json and crashes.

This the the plugin installing. Composer has to install the plugin before the plugin can register for events and by the time it registers the events have already fired. I would like to figure out how to emit a message about this at install time telling the user that they need to run composer a second time to see benefit. This is probably worth a separate feature-enhancement ticket.

**Comment by astax-t** [comment]
Ok, having to run it twice is not that big issue.

But the original problem is still there with the latest versions of composer and this plugin.

To replicate, create empty git repository, add and commit `composer.json` and `composer.local.json` from https://github.com/wikimedia/composer-merge-plugin/issues/26#issuecomment-100363870 and then call `composer update`.

The text is slightly different now:

```
E:\test> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing wikimedia/composer-merge-plugin (dev-master 98c31a2)
    Cloning 98c31a299aa68a1540e83aaa10cb3c58395b0b96

Writing lock file
Generating autoload files

  [UnexpectedValueException]
  Expected instance of RootPackage, got Composer\Package\RootAliasPackage

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins]
[--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies]
[-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable]
[--prefer-lowest] [packages1] ... [packagesN]
```
