### ISSUE TITLE
Merge "replace" option

### ISSUE THREAD

**Issue by mbrodala** [wikimedia/composer-merge-plugin#35]
In addition to the existing options please consider merging the [`replace` option](https://getcomposer.org/doc/04-schema.md#replace), too.

**Comment by far-blue** [comment]
+1

In a situation where there is a 'live' composer configuration that needs overriding for a feature branch or a local dev environment the main use case is likely to be replacing package defines with others rather than attempting to resolve both defines.

**Comment by far-blue** [comment]
I've thrown together a basic version of the functionality in this pull request: #44

**Comment by bd808** [comment]
@far-blue I think that @mbrodala is asking for something a bit different than your patch provides. I think they are asking for the plugin to collect and merge together any and all "replace" package links declared in the various composer.json files.

That doesn't make your proposed patch any less useful however. Can you create a new issue to track your feature request for "later" composer.json definitions to override prior ones and update your pull request to point at it instead?

**Comment by mbrodala** [comment]
@bd808 Indeed, I was asking something akin to the currently supported options. Example:

*composer.json*:

```json
{
  "require": {
    "typo3/cms": "~6.2"
  },
  "extra": {
    "merge-plugin": {
      "include": [
        "composer.tests.json"
      ]
    }
  }
}
```

**composer.tests.json**:

```json
{
  "replace": {
    "typo3/cms-composer-installers": "*"
  }
}
```

Upon resolving dependencies, the `typo3/cms-composer-installers` should be replaced by the current root package.

**Comment by far-blue** [comment]
The pull request associated with this issue is now #46
