### ISSUE TITLE
Don't silently ignore when declared inclusion files don't exist

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/composer-merge-plugin#37]
When having a `composer.local.json` like follows:
```json
{
    "extra": {
        "merge-plugin": {
            "include": [
                "foo/bar/composer.json"
            ]
        }
    }
}
```

Where `foo/bar` does not exist, there is no error from running `composer update`.

For MediaWiki core this is convenient since existence of `composer.local.json` itself is optional. And things like `*` matches for subdirectories may also legitimately yield no matches. But when specifying an exact file it should report an error to catch regressions, typos etc.

This is a known problem in many libraries that pull everything through pattern-matchers (same in Grunt often), but should be fixable hopefully.

**Comment by bd808** [comment]
@Krinkle wold you want a hard error or just a visible warning? If we went with a hard error I think I'd want it to be opt-in behavior via a new configuration setting. As you point out we use an explicit filename that is optional in the MediaWiki composer.json.

**Comment by Krinkle** [comment]
Perhaps we can borrow the PHP-ism of `require` vs `include` as alternate key?
