### ISSUE TITLE
post-install step does not rebuild optimized composer autoloader

### ISSUE THREAD

**Issue by legoktm** [wikimedia/composer-merge-plugin#41]
composer.json:
```
{
	"require": {
		"wikimedia/composer-merge-plugin": "1.2.0",
		"psr/log": "1.0.0"
	},
	"config": {
		"classmap-authoritative": true,
		"prepend-autoloader": false,
		"optimize-autoloader": true
	},
	"extra": {
		"merge-plugin": {
			"include": [
				"composer.local.json"
			]
		}
	}
}
```
composer.local.json
```
{
	"require": {
		"zordius/lightncandy": "0.21"
	}
}
```

Run `composer install`. Look at vendor/composer/autoload_classmap.php and see that the Psr\Log* entries are not there. This becomes an issue when the "classmap-authoritative" option is used because it does not fallback to the psr0 or psr4 autoloader.

**Comment by bd808** [comment]
This is controlled by the the `$optimizeAutoloader` protected member in `Composer\Installer`. There is no getter for this member (and several others) that would let us copy the value over to the new Installer instance we make in `onPostInstallOrUpdate()`. 

Of all the flags set by `InstallCommand` we only copy  dev mode to our new instance. I think we are going to have to get creepy and use PHP reflection API to access these flags and copy them over.

```
        $install
            ->setDryRun($input->getOption('dry-run'))
            ->setVerbose($input->getOption('verbose'))
            ->setPreferSource($preferSource)
            ->setPreferDist($preferDist)
            ->setDevMode(!$input->getOption('no-dev'))
            ->setDumpAutoloader(!$input->getOption('no-autoloader'))
            ->setRunScripts(!$input->getOption('no-scripts'))
            ->setOptimizeAutoloader($optimize)
            ->setIgnorePlatformRequirements($input->getOption('ignore-platform-reqs'))
        ;
```
