### ISSUE TITLE
This is not a "at runtime" plugin.

### ISSUE THREAD

**Issue by binwiederhier** [wikimedia/composer-merge-plugin#52]
If I understand correctly, the plugin tries to load the "include" composer.json files at build time (`composer update` and `composer install`). If the composer.json file does not exist during build time or the dependencies are not initialized, the autoloader generation will fail. 

IMHO, this is *not* a runtime plugin. A runtime plugin would not care about the non-existing composer.json file during build time. It would load the composer.json file at runtime and load dependencies when they are needed.

Maybe it's me. Am I doing something wrong?

**Comment by bd808** [comment]
> Maybe it's me. Am I doing something wrong?

Maybe? Did you install the plugin globally for your Composer install (eg `composer global require wikimedia/composer-merge-plugin`)? I have never tested that scenario.

As you state the primary intent of this plugin is to alter the behavior of Composer during the build of the `vendor` directory and it's associated `autoloader.php` script. The use of "at runtime" in README.md is meant to mean the runtime of Composer, not the runtime of the application that Composer is being used to manage.

> It would load the composer.json file at runtime and load dependencies when they are needed.

Downloading new Composer packages during a web application's runtime would be both insecure and slow. PHP's autoloading mechanism will dynamically load PHP source files at runtime when the classes they contain are needed.

This plugin is intended to assist in creating that autoloader (and obtaining the files it loads) for projects where some dependencies are controlled upstream and others are controlled in the local deployment. Most specifically it was created to help with installation of [MediaWiki](http://www.mediawiki.org) which has core Composer managed library requirements and optional libraries and extensions which may also be managed via Composer.
