### ISSUE TITLE
composer update --dry-run

### ISSUE THREAD

**Issue by thewilkybarkid** [wikimedia/composer-merge-plugin#55]
If I run `composer update --dry-run` to find out if there's any newer versions available, it appears to not merge in the other `composer.json` files, so lists all dependencies included there as being removed. This doesn't happen when running `composer update`, which does correctly update all of them.

**Comment by bd808** [comment]
The plugin does most of it's work in response to the `ScriptEvents::POST_INSTALL_CMD` or `ScriptEvents::POST_UPDATE_CMD` events. The `--dry-run` mode [disables script events](https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L171) so no trigger events are received by the plugin. Looking at [Composer\Installer](https://github.com/composer/composer/blob/master/src/Composer/Installer.php)'s code, it appears that no events are dispatched in `--dry-run` mode at all as all usage of the event dispatcher is guarded by either `if (!$this->dryRun) {` or `if ($this->runScripts) {`.

I don't think there is anything we can do to correct this. You could open [an upstream issue](https://github.com/composer/composer/issues) to see if they might be interested in changing this behavior by extending the event system to include a `dryRun` status flag or alternate events.

**Comment by Soullivaneuh** [comment]
@thewilkybarkid In this case, https://github.com/composer/composer/issues/4650 may interest you. :+1:

**Comment by Soullivaneuh** [comment]
@bd808 In this case, https://github.com/composer/composer/issues/4650 may interest you. :+1:
