### ISSUE TITLE
Latest version of composer includes 'path' option

### ISSUE THREAD

**Issue by leevigraham** [wikimedia/composer-merge-plugin#72]
Does this make composer-merge-plugin un-needed? https://getcomposer.org/doc/05-repositories.md#path

**Comment by legoktm** [comment]
From what I can tell, that allows you to use local packages on your filesystem and add dependencies upon those. It wouldn't do merging of dependencies, you'd still have to add that package as a dependency. I haven't tested it to verify yet.
