### ISSUE TITLE
"The requested package *** could not be found." when require-dev has duplicate entries

### ISSUE THREAD

**Issue by FlorianSW** [wikimedia/composer-merge-plugin#90]
Consider the following scenario:
You have a MediaWiki wiki with the SyntaxHighlight_GeSHi extension installed. Both, MediaWiki and SyntaxHighlight_GeSHi uses composer to install additional dependencies, dev-requirements and libraries. With the 1.27.0-wmf.4 branch, you'll have the following line in SyntaxHighlight_GeSHi:
https://github.com/wikimedia/mediawiki-extensions-SyntaxHighlight_GeSHi/blob/wmf/1.27.0-wmf.4/composer.json#L9
```"mediawiki/mediawiki-codesniffer": "0.5.0"```

in the require-dev section. So far so good. Now, MediaWiki has the following line (same branch):
https://github.com/wikimedia/mediawiki/blob/wmf/1.27.0-wmf.4/composer.json#L42
```"mediawiki/mediawiki-codesniffer": "0.4.0",```

What happens, if you include/merge both composer.jsons and run composer update. You'll get:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mediawiki/mediawiki-codesniffer 0.5.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

I'm pretty sure, that the correct way to handle this is to stop the update process, but I wish a better error message, e.g. from composer-merge-plugin, that the dependency from one included json already exists with another version constraint, so you'll get a better indication where you have to look for the/a problem :)

**Comment by bd808** [comment]
This exact issue was the reason that @legoktm opened #85 (Option to not merge require-dev sections). When we ship v1.3.0 we will be able to use the new `"merge-dev": false` setting in MediaWiki's composer.json to keep Composer from processing require-dev sections in included files.

As for making a nicer error message, that would be nice as well but would need to be done upstream in Composer. This error message comes from [Composer's Solver](https://github.com/composer/composer/blob/4f934d928260e126b5d06392e12ee20fae258232/src/Composer/Installer.php#L521-L528). At the level of the Solver there is no knowledge of where the required versions came from but it probably could do a better job of explaining that there have been conflicting versions of the same package requested.

**Comment by bd808** [comment]
If you run composer in verbose mode (`composer update -v`) you should actually see a message from composer-merge-plugin about a duplicate package definition being deferred to the solver.
