### ISSUE TITLE
Can haz 1.3.0 release?

### ISSUE THREAD

**Issue by cweagans** [wikimedia/composer-merge-plugin#94]
https://github.com/wikimedia/composer-merge-plugin/issues/50 keeps biting us. We'd really love to update :)

**Comment by bd808** [comment]
Working on it. :) We just got the last open 1.3.0 related patches merged about an hour ago.

**Comment by cweagans** [comment]
Awesome. Anything left that an outsider can help with?

**Comment by bd808** [comment]
https://packagist.org/packages/wikimedia/composer-merge-plugin#v1.3.0

**Comment by cweagans** [comment]
<3 thanks!
