### ISSUE TITLE
When a merged composer.json changes running composer install doesn't get the new dependencies

### ISSUE THREAD

**Issue by alexpott** [wikimedia/composer-merge-plugin#96]
Steps to reproduce:
1. git clone --branch 8.1.x http://git.drupal.org/project/drupal.git
2. cd drupal
3. git checkout 87986e3 composer.lock
4. rm -rf vendor/paragonie (yes it weird we include our dependencies in the git repo but that's not part of this problem)
5. composer install

Expected result:
Installing paragonie/random_compat (1.1.4)

Actual result:
Nothing to install or update

**Comment by neclimdul** [comment]
I'm wondering if this is just a discrepancy in reporting rather then a missing feature. Composer doesn't behave this way either but it does report the missing dependency where as merge doesn't.

Add dependency to ```core/composer.json``` and run install:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
```

Add dependency to ```composer.json``` and run install:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
```

The important distinction is ```Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.``` which basically tells someone your application is broken and you can follow the message on the internet and find a solution. The first looks perfectly fine but the installation might be broken.

**Comment by alexpott** [comment]
@neclimdul nice work - yep that's exactly my point - the hash check needs work the same regardless of where the dependency was added.

**Comment by pschulz** [comment]
Hey guys, any solution for this issue?
I have the same issue here, but I also found an interesting statement in `composer help install`, saying that 

>   The install command reads the composer.lock file from
  the current directory, processes it, and downloads and installs all the
  libraries and dependencies outlined in that file. If the file does not
  exist it will look for composer.json and do the same.

This means that composer is not intended to and will never add entries to the lockfile, if something is missing there but defined in the composer.json files. The only thing that works is `composer update`, but with the lack that any "pinned"/locked version will be updated as well - and this would equal the case if no composer.lock file exists at all.

To me it sounds like that composer-merge-plugin must/should either support merging *.lock files or break with the rules given by composer.

**Comment by bd808** [comment]
Fixing this via composer-merge-plugin would require some core api changes in the upstream Composer project. The out of date lock file warning happens based on a comparison of data integrity hashes stored in the lock file and the same hash computed on the composer.json file. Composer-merge-plugin has no way to update the computed hash either at initial install or during the runtime checks.

Broadly speaking, lock based installs are outside the intended scope for composer-merge-plugin. Our core use case is allowing a mixture of upstream requirements and local additions in a single deployment. People have figured out how to use the tool to do a heck of a lot more than the original vision which is awesome, but there are a lot of limitations on what can be done from the plugin/callback API exposed by Composer itself. This use case of `composer install` based locked dependency repair falls pretty squarely into an area that can only be solved upstream effectively.

**Comment by redgluten** [comment]
Applying `composer update --lock` on the root does install the dependencies as well as… well updating the lock thus providing a proper state for `composer install` based workflows. Should we add this to the README maybe?

**Comment by bd808** [comment]
@redgluten that sounds like a great tip to provide to our users. Please open a pull request to update the docs. :)
