### ISSUE TITLE
Incompatibility with some plugins (processing merge after?)

### ISSUE THREAD

**Issue by lpalgarvio** [wikimedia/composer-merge-plugin#99]
Hello

The merge process of the composer-merge-plugin is probably happening after some plugins, meaning these don't get the merged json from merge-plugin.

Detected situations:
- drupal-libraries-installer-plugin
  https://github.com/generalredneck/drupal-libraries-installer-plugin
  https://github.com/generalredneck/drupal-libraries-installer-plugin/issues/3
- composer-custom-directory-installer
  https://github.com/mnsami/composer-custom-directory-installer
  https://github.com/mnsami/composer-custom-directory-installer/issues/16

I did some research and posted on the aforementioned issues.

**Comment by bd808** [comment]
It looks like there is a priority option that can be given when subscribing to events. Maybe if we load early enough our changes will be available to other plugins.

**Comment by lpalgarvio** [comment]
fantastic :) :+1:

**Comment by cronfy** [comment]
Probably I have same issue with `fxp/composer-asset-plugin`. I can't get `"extra": { "asset-installer-paths": {...} }` from included composer.json files to work, even with this config:

```
      "replace": true,
      "merge-extra": true,
      "merge-extra-deep": true
```

Looks like `fxp/composer-asset-plugin` reads it's configuration from main composer.json before other composer.json files are merged.
